services:
  php:
    build:
      args:
        user: xxxxxx_user
        uid: 1000
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: xxxxxx-php
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - xxxxxx_network

  nginx:
    image: nginx:alpine
    container_name: xxxxxx-nginx
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80" # To avoid conflict with another running container. Change to 8080:80 for example.
    depends_on:
      - php
    networks:
      - xxxxxx_network

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432 # To avoid conflict with another running container. Change to 5433:5432 for example. Remember to use 5433 in your DBMS.
    networks:
      - xxxxxx_network
   
networks:
  xxxxxx_network:
    driver: bridge

volumes:
  xxxxxx_dbdata: